### ISSUE TITLE
AntBot get a lil quirky at night

### ISSUE THREAD

**Issue by ryyybaaa** [FuncFusion/antbot#1]
ваша нейронная сеть обрелф сознание и делает людей грязными. исправьте это, пока не стало слишком поздно
![image](https://github.com/user-attachments/assets/793db05c-761e-4d62-ba67-308fe9ede0b7)

**Comment by bth123** [comment]
Works as intended.

**Comment by ryyybaaa** [comment]
совсем ёбу дали? он уже подбирает код для запуска межконтинентальных ядерных ракет. это приведёт к всемирной катастрофе
![image](https://github.com/user-attachments/assets/32ff2e70-2337-4373-aa06-38c57c9ded21)

**Comment by bth123** [comment]
Still works as intended

**Comment by ryyybaaa** [comment]
sori me not speak amerika
